### ISSUE TITLE
Time text wraps at 08:08 in 24-hour mode

### ISSUE THREAD

**Issue by 48kRAM** [ygalanter/PebStyle#1]
I use my pebble time in digital, 24-hour mode. I noticed at 08:08 this morning that the time text wrapped onto a second line. It appears that the text is at its widest at that time and just barely doesn't fit on one line.

**Comment by ygalanter** [comment]
That was embarrassing. Please get v2.14 - it should have that issue fixed.

**Comment by 48kRAM** [comment]
Installed - thank you! I'll try to remember to watch it tomorrow morning :)
